k-shape and k-means added. Its corresponding test has been added too
shapelets/khiva-r pull request #26
Opened 2019-02-27 15:39 UTC by dcuestam

Make sure you have checked _all_ steps below.

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits have been squashed if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

## License
- [ ] Add a [Mozilla Public License 2.0 license header](http://mozilla.org/MPL/2.0/) to all the new files.

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.

2019-02-27 16:04 UTC, avilchess requested changes

2019-02-27 16:04 UTC, avilchess commented on R/clustering.R
> +#'
Set reference to paper

2019-02-27 16:04 UTC, avilchess commented on R/clustering.R
> +#'
Set reference to paper

2019-02-27 16:11 UTC, avilchess submitted a review, later dismissed

2019-03-01 11:34 UTC, otorreno requested changes

2019-03-01 11:34 UTC, otorreno commented on R/clustering.R
> +#' @param max_iterations The maximum number of iterations allowed.
maxIterations

2019-03-01 11:34 UTC, otorreno commented on R/clustering.R
> +#' @param max_iterations The maximum number of iterations allowed.
Same here

2019-03-01 12:46 UTC, avilchess requested changes

2019-03-01 12:46 UTC, avilchess commented on tests/testthat/test_clustering.R
> +        1.8711,-0.7825,
David, please keep 1 element per line.

2019-03-01 12:46 UTC, avilchess commented on tests/testthat/test_clustering.R
> +        -0.7825,-0.6278,
idem.

2019-03-01 12:54 UTC, avilchess submitted a review, later dismissed

2019-03-01 13:11 UTC, otorreno approved these changes
LGTM

2019-03-05 08:15 UTC, merged